name: "Terraform"

on:
  push:
    branches:
      - "feature-*"
  #pull_request:

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  createPR:
    name: "Create PR"
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: homolog